#ifdef SPANISH
	#define STR0001 "Seguro Social"
	#define STR0002 "Seguro Social Empleador"
	#define STR0003 "Seguro Social Vacaciones"
	#define STR0004 "Descuento de Vacaciones en Planilla"
	#define STR0005 "Bonificacion de Vacaciones"
	#define STR0006 "Bonificacion Vencida Rescision"
	#define STR0007 "Media Horas Bonificacion"
	#define STR0008 "Media Valor Bonificacion"
	#define STR0009 "Bonificacion Proporcional Rescision"
	#define STR0010 If( cPaisLoc == "BOL", "Provision Acumulada Prima Anual", "Provision Acumulada Utilidad" )
	#define STR0011 If( cPaisLoc == "BOL", "Provision Prima Anual", "Provision Utilidad" )
	#define STR0012 "Provision Acumulada Bonificacion Vacaciones"
	#define STR0013 "Provision Acumulada Adic. Bonif. Vacaciones"
	#define STR0014 "Provision Adicional Bonificacion Vacaciones"
	#define STR0015 "Provision Bonificacion Vacaciones"
	#define STR0016 "Baja Provision Bonificacion Vacaciones"
	#define STR0017 "Baja Provision Bonificacion Vacaciones Rescision"
	#define STR0018 "Remuneracion Redondeo Utilidad"
	#define STR0019 "Antiguidad Pagada en la Rescision"
	#define STR0020 "Intereses Antiguidad Pagados en la Rescision"
	#define STR0021 "Intereses Diferencia Antiguidad"
	#define STR0022 "Neto Utilidad"
	#define STR0023 "Neto Anticipo Utilidad"
	#define STR0024 "Baja Provision Utilidad"
	#define STR0025 "Baja Provision Utilidad Rescision"
	#define STR0026 "Base Cesantia"
	#define STR0027 "Base Intereses de Cesantia"
	#define STR0028 "Cesantia"
	#define STR0029 "Intereses de Cesantia"
	#define STR0030 "Baja Provision Adicional Bonificacion de Vacaciones"
	#define STR0031 "Baja Provision Adicional Bonificacion de Vacaciones Rescision"
	#define STR0032 "Dias de Descanso en las Vacaciones"
	#define STR0033 "Diferencia de Premios por Servicios"
	#define STR0034 "Acumulado de Indemnizacion de Rescision"
	#define STR0035 "Auxilio Paternidad"
	#define STR0036 "Rectificacion de Remuneracion"
	#define STR0037 "Fondo Nacional de Empleo"
	#define STR0038 "Insuficiencia de Saldo Anticipo Provision"
	#define STR0039 "Base Contribucion Patronal Salario Familia"
	#define STR0040 "Valor Contribucion Patronal Salario Familia"
	#define STR0041 "Base Aportes Voluntarios"
	#define STR0042 "Base Ingresos Laborales"
	#define STR0043 "Fondo Nacional de Empleo"
	#define STR0044 "Aguinaldo sobre Vacaciones No Efectivadas"
	#define STR0045 "Adicional sobre Vacaciones Proporcionales"
	#define STR0046 "Diferencia Base Jubilacion Empleado"
	#define STR0047 "Diferencia Base Obra Social Empleado"
	#define STR0048 "Diferencia Base INSSJP Empleado"
	#define STR0049 "Diferencia Base ART Empleado"
	#define STR0050 "Diferencia FNE"
	#define STR0051 "Diferencia Salario Familia Patronal"
	#define STR0052 "Diferencia Base Jubilacion Patronal"
	#define STR0053 "Diferencia Base Obra Social Patronal"
	#define STR0054 "Diferencia Base INSSJP Patronal"
	#define STR0055 "Salario Integral"
	#define STR0056 "Descuento de Dias de Vacaciones del Salario"
	#define STR0057 "Aguinaldo Base Inss/Jubilacion Empleado"
	#define STR0058 "Aguinaldo Base Inss/Jubilacion Empresa"
	#define STR0059 "Aguinaldo Inss/Jubilacion Empleado"
	#define STR0060 "Aguinaldo Inss/Jubilacion Empresa"
	#define STR0061 "Aguinaldo Obra Social Empleado"
	#define STR0062 "Aguinaldo Obra Social Empresa"
	#define STR0063 "Aguinaldo Obra Social Empleado"
	#define STR0064 "Aguinaldo Obra Social Empresa"
	#define STR0065 "Aguinaldo ANSSAL Empleado"
	#define STR0066 "Aguinaldo ANSSAL Empresa"
	#define STR0067 "Aguinaldo Base InssJP/Ley 19032 Empleado"
	#define STR0068 "Aguinaldo Base InssJP/Ley 19032 Empresa"
	#define STR0069 "Aguinaldo InssJP/Ley 19032 Empleado"
	#define STR0070 "Aguinaldo InssJP/Ley 19032 Empresa"
	#define STR0071 "Aguinaldo DIF. Obra Social Empleado"
	#define STR0072 "Aguinaldo DIF. Obra Social Empresa"
	#define STR0073 "Aguinaldo Base ART"
	#define STR0074 "Aguinaldo ART Empresa"
	#define STR0075 "Base Exenta Primas"
	#define STR0076 "VAC. Base Inss/Jubilacion Empleado"
	#define STR0077 "VAC. Base Inss/Jubilacion Empresa"
	#define STR0078 "VAC. Inss/Jubilacion Empresa"
	#define STR0079 "VAC. DIF. Obra Social Empresa"
	#define STR0080 "VAC. Base Obra Social Empresa"
	#define STR0081 "VAC. Obra Social Empresa"
	#define STR0082 "VAC. ANSSAL Empresa"
	#define STR0083 "VAC. Base InssJP/Ley 19032 Empresa"
	#define STR0084 "VAC. InssJP/Ley 19032 Empresa"
	#define STR0085 "VAC. Base ART"
	#define STR0086 "VAC. ART Empresa"
	#define STR0087 "Descuento de Dias Rescision"
	#define STR0088 "AFP Empresa - Ausencias"
	#define STR0089 "Vacaciones compensadas"
	#define STR0090 "Promedio de vacaciones compensadas"
	#define STR0091 "Base Dias No Habiles"
	#define STR0092 "Compensacion en la Rescision"
	#define STR0093 "Ayuda de Costo Nac / Extranj"
	#define STR0094 "Ayuda de Costo Formacion"
	#define STR0095 "Desc Vacaciones Mes CVG"
	#define STR0096 "Base Vacaciones Mes Siguiente CVG"
	#define STR0097 "Valor del Impuesto Determinado"
	#define STR0098 "Valor Impuesto determinado vacaciones"
	#define STR0099 "Valor Impuesto determinado anticipo"
	#define STR0100 "Remuneracion de vacaciones"
	#define STR0101 "Dias de Vacaciones no disfrutadas en la Rescision"
	#define STR0102 "Neto Segunda Moneda"
	#define STR0103 "Base FSP"
	#define STR0104 "Quiebra de Contrato - Rescision"
	#define STR0105 "Base FSP Vacaciones"
	#define STR0106 "Desc.Dias Anticipados en Vacaciones"
	#define STR0107 "Base AFP"
	#define STR0108 "Base AFP Vacaciones"
	#define STR0109 "Base Total Jubilacion "
	#define STR0110 "Base Total Obra Social"
	#define STR0111 "Base Total Ley"
	#define STR0112 "Base Total ART"
	#define STR0113 "Base AFP Contribucion Adicional"
	#define STR0114 "Base AFP Contribucion Voluntaria"
	#define STR0115 "CFDCT "
	#define STR0116 "OFATMA-Seguro Contra Accidente Trabajo "
	#define STR0117 "Pension SNP"
	#define STR0118 "Pago.Descanso Medico"
	#define STR0119 "Base Contribucion de IRRF (Otras Empresas)"
	#define STR0120 "Base Descuento de IRRF (Otras Empresas)"
	#define STR0121 "Base SCRT"
	#define STR0122 "SCRT Pension"
	#define STR0123 "SCRT Salud"
	#define STR0124 "Base SENATI"
	#define STR0125 "SENATI"
	#define STR0126 "Seguro de Vida Empresa"
	#define STR0127 "Devolucion Reliquidacion de Ganancia"
	#define STR0128 "Devolucion Reliquidacion de Ganancia"
	#define STR0129 "Compensacion por Tiempo de Servicio"
	#define STR0130 "Compensacion por Tiempo de Servicio - Acumulado Semestre Ant."
	#define STR0131 "Devolucion de ganancia ya liquidada."
	#define STR0132 "Retención de ganancia ya liquidada."
	#define STR0133 "Base Compensacion por Tiempo de Servicio"
	#define STR0134 "Fondo de Ayuda / Gratificacion Extraordinaria"
	#define STR0135 "Neto Gratificacion"
	#define STR0136 "Base Gratificacion"
	#define STR0137 "Diferencia Gratificacion - Remuneracion"
	#define STR0138 "Diferencia Gratificacion - Descuento"
	#define STR0139 "Base Promedio Vacaciones Valor"
	#define STR0140 "Acumulado CTS (Semestre)"
	#define STR0141 "Acumulado CTS (Mes)"
	#define STR0142 "Acumulado Gratificaciones (Semestre)"
	#define STR0143 "Acumulado Gratificaciones (Mes)"
	#define STR0144 "Baja Provision Gratificaciones"
	#define STR0145 "Baja Provision Compensacion por Tiempo de Servicio "
	#define STR0146 "Sistema Privado de Pension - Prima de Seguros"
	#define STR0147 "Sistema Privado de Pension - Comision Base"
	#define STR0148 "Base Sistema Privado de Pension - Prima de Seguros"
	#define STR0149 "AFP Asumido"
	#define STR0150 "Utilidades - Dias Trabajados"
	#define STR0151 "Base Utilidades - Remuneracion"
	#define STR0152 "Utilidades - Remuneracion"
	#define STR0153 "Promedio de Licencias"
	#define STR0154 "Aporte Voluntario con Final Provisional"
	#define STR0155 "Aporte Voluntario sin Final Provisional"
	#define STR0156 "Deduccion IR"
	#define STR0157 "Base Tot Pat Jubilacion"
	#define STR0158 "Base Tot Pat InssJP/Ley 19032"
	#define STR0159 "Base Tot Pat Asignacion Familiar"
	#define STR0160 "Base Tot Pat FNE"
	#define STR0161 "Aguinaldo Base Tot Pat Jubilacion"
	#define STR0162 "Aguinaldo Base Tot Pat InssJP/Ley 19032"
	#define STR0163 "Aguinaldo Base Tot Pat Asignacion Familiar"
	#define STR0164 "Aguinaldo Base Tot Pat FNE"
	#define STR0165 "VAC.Base Tot Pat Jubilacion"
	#define STR0166 "FER.Base Tot Pat InssJP/Ley 19032"
	#define STR0167 "Subsidio Escolar"
	#define STR0168 "Bonificacion por Altitud"
	#define STR0169 "Bonificacion por Altura"
	#define STR0170 "Bonificacion Unificada de Construccion Civil"
	#define STR0171 "Base de Ganancia Neta Negativa"
	#define STR0172 "Horas extras - informativo"
	#define STR0173 "Conafovicer"
	#define STR0174 "Conafovicer"
	#define STR0175 "Base Compensacion Vacaciones"
	#define STR0176 "Compensacion Vacaciones"
	#define STR0177 "Devolucion Ganancia en el Anticipo"
	#define STR0178 "Bonificacion Ley Nº 29351 - Essalud"
	#define STR0179 "Bonificacion Ley Nº 29351 - EPS"
	#define STR0180 "Base Credito Educativo"
	#define STR0181 "Valor Credito Educativo"
	#define STR0182 "Base Capacitacion Profesional"
	#define STR0183 "Valor Capacitacion Profesional"
	#define STR0184 "Base Credito Educativo Vacaciones"
	#define STR0185 "Valor Credito Educativo Vacaciones"
	#define STR0186 "Base Capacitacion Profesional Vacaciones"
	#define STR0187 "Valor Capacitacion Profesional Vacaciones"
	#define STR0188 "Impuesto de Renta Otras Empresas"
	#define STR0189 "Base IR Proyectada "
	#define STR0190 "Base Valor Seg. Social Proyectado"
	#define STR0191 "2º Aguinaldo"
	#define STR0192 "Neto 2º Aguinaldo"
	#define STR0193 "Bonificacion Agua"
	#define STR0194 "Devolucion Ganancia RG 2867"
	#define STR0195 "Aporte Adic. Const. Civil - Empleado"
	#define STR0196 "Aporte Adic. Const. Civil - Empresa"
	#define STR0197 "Base Indemnizacion Rescision"
	#define STR0198 "Ayuda de costo hasta el Limite en Portugal (Exento)"
	#define STR0199 "Ayuda de costo superior al Limite en Portugal (Tributado)"
	#define STR0200 "Ayuda de costo hasta el Limite en el extranjero (Exento)"
	#define STR0201 "Ayuda de costo superior al Limite en el extranjero (Tributado)"
	#define STR0202 "Valor utilidades familia"
	#define STR0203 "Base Aguinaldo en la Rescision"
	#define STR0204 " Deduccion Discapacitado"
	#define STR0205 "Deduccion 3a. Edad"
	#define STR0206 "14 Salario en la Rescision"
	#define STR0207 "Base de Calculo de Aporte Sindical"
	#define STR0208 "Dias adicionales gozados"
	#define STR0209 "Base Despido Inoportuno"
	#define STR0210 "Despido Inoportuno"
	#define STR0211 "Base Aporte Patronal Excedente"
	#define STR0212 "Aporte Adicional AFP"
	#define STR0213 "Valor excedente de indemnizacion tributable de IRS"
	#define STR0214 "Base de Calculo para Vacaciones"
	#define STR0215 "Acumulado Aguinaldo (Mes)"
	#define STR0216 "Acumulado Aguinaldo (Ano)"
	#define STR0217 "Acumulado 2º Aguinaldo (Mes)"
	#define STR0218 "Acumulado 2º Aguinaldo (Ano)"
	#define STR0219 "Base Fondo de Reserva"
	#define STR0220 "Fondo de Reserva"
	#define STR0221 "Fondo de Reserva - IESS"
	#define STR0222 "Dias Trabajados p/ Utilidades"
	#define STR0223 "Dias Trabajados Cargas p/ Utilidades"
	#define STR0224 "Dev. Ganancia RG 2867 Vac. "
	#define STR0225 "Base Fondo de Reserva - Vacaciones"
	#define STR0226 "Fondo de Reserva - Vacaciones"
	#define STR0227 "Fondo de Reserva IESS - Vacaciones"
	#define STR0228 "Base AFP Aportacion Solidaria"
	#define STR0229 "AFP Aportacion Solidario"
	#define STR0230 "Base Integral Vacaciones "
	#define STR0231 "Base Proporcional Vacaciones"
	#define STR0232 "Dev. Ganancia Vac"
	#define STR0233 "Pagos de Intereses de Antiguedad"
	#define STR0234 "Base Indemnizacion Finalizacion Anticipada de Contrato"
	#define STR0235 "Valor Indemnizacion Termino Anticipado de Contrato"
	#define STR0236 "Deb. Medicina Pre-paga empleado"
	#define STR0237 "Deb. Medicina Pre-paga empresa"
	#define STR0238 "Falta de domingo"
	#define STR0239 "Baja Provision Indemnizacion "
	#define STR0240 "Prórroga de la Lic. Maternidad"
	#define STR0241 "Pago de Promedio Prórroga de la Lic Maternidad"
	#define STR0242 "Vacaciones Pagadas"
	#define STR0243 "Baja Provisión Cesantía"
	#define STR0244 "Baja Provisión Intereses de Cesantía"
	#define STR0245 "Baja Provisión Primas"
	#define STR0246 "Indemnización por Embarazo"
	#define STR0247 "UPC Adicional"
	#define STR0248 "Base Total Fondo Solidario"
	#define STR0249 "Adicional de Obra Social - Empleado"
	#define STR0250 "Adicional ANSSAL - Empleado"
	#define STR0251 "Adicional Obra Social - Patronal"
	#define STR0252 "Adicional ANSSAL - Patronal"
	#define STR0253 "Adicional Obra Social Vacaciones  - Empleado"
	#define STR0254 "Adicional ANSSAL Vacaciones  - Empleado"
	#define STR0255 "Adicional Obra Social Vacaciones  - Patronal"
	#define STR0256 "Adicional ANSSAL  Vacaciones  - Patronal"
	#define STR0257 "Adicional Obra Social  SAC  - Empleado"
	#define STR0258 "Adicional ANSSAL SAC  - Empleado"
	#define STR0259 "Adicional Obra Social  SAC  - Patronal"
	#define STR0260 "Adicional ANSSAL SAC  - Patronal"
	#define STR0261 "Base Dif. Obra Social Vacaciones"
	#define STR0262 "Deb. Dif.  Plan de Salud"
	#define STR0263 "Base Valor Ganancia Vacaciones"
	#define STR0264 "BS Adic Obra Social Vaciones - Empleado"
	#define STR0265 "BS Adic ANSSAL Vaciones - Empleado"
	#define STR0266 "Devolucíon de SAC Pago superior al empleado"
	#define STR0267 "Gratificacion Extraordinaria"
	#define STR0268 "Gratificacion Extraordinaria - Diferencia"
	#define STR0269 "Bonus Cuota Cero"
	#define STR0270 "Gratificacion Extraordinaria en la Rescision"
	#define STR0271 "Infotep Utilidades"
	#define STR0272 "Infotep Nomina"
	#define STR0273 "Base Salario para Licencias (Maternidad, Enfermedad y Subsidio Seguro)"
	#define STR0274 "Base Salario para Quinquenio"
	#define STR0275 "Quinquenio por Procedimiento"
	#define STR0276 "Quinquenio fuera del plazo"
	#define STR0277 "Subsidio de Frontera"
	#define STR0278 "Deduccion por Dependientes"
	#define STR0279 "Base CNS Seguro a corto prazo"
	#define STR0280 "Distribucion de ganancia 1ª Cuota (Descuento)"
	#define STR0281 "Ded.Asignacion Maternidad"
	#define STR0282 "Peligrosidad sobre conceptos"
	#define STR0283 "Insalubridad sobre conceptos"
	#define STR0284 "Periodo de un ano sobre conceptos"
	#define STR0285 "Bienio sobre conceptos"
	#define STR0286 "Trienio sobre conceptos"
	#define STR0287 "Cuatrienio sobre conceptos"
	#define STR0288 "Quinquenio sobre conceptos"
	#define STR0289 "ATS Aguinaldo"
	#define STR0290 "ATS Aguinaldo sobre conceptos"
	#define STR0291 "Peligrosidad Aguinaldo"
	#define STR0292 "Peligrosidad Aguinaldo sobre conceptos"
	#define STR0293 "Insalubridad Aguinaldo"
	#define STR0294 "Insalubridad Aguinaldo sobre conceptos"
	#define STR0295 "Adicional Cargo de Confianza Aguinaldo"
	#define STR0296 "Adicional Transferencia Aguinaldo"
	#define STR0297 "ATS Vacaciones Mes"
	#define STR0298 "ATS Vacaciones Mes Siguiente"
	#define STR0299 "ATS Vacaciones Mes s/ Conceptos"
	#define STR0300 "ATS Vacaciones Mes Sig. s/ Conceptos"
	#define STR0301 "Peligrosidad Vacaciones Mes"
	#define STR0302 "Peligrosidad Vacaciones Mes Sig."
	#define STR0303 "Peligrosidad Vacaciones Mes s/ Conceptos"
	#define STR0304 "Peligrosidad Vacaciones Mes Sig. s/ Conceptos"
	#define STR0305 "Insalubridad Vacaciones Mes"
	#define STR0306 "Insalubridad Vacaciones Mes Sig."
	#define STR0307 "Insalubridad Vacaciones Mes s/ Conceptos"
	#define STR0308 "Insalubridad Vacaciones Mes Sig. s/ Conceptos"
	#define STR0309 "Adic. Cargo Confianza Vacaciones Mes"
	#define STR0310 "Adic. Cargo Confianza Vacaciones Mes Sig."
	#define STR0311 "Adic. Transferencia Vacaciones Mes"
	#define STR0312 "Adic. Transferencia Vacaciones Mes Sig."
	#define STR0313 "ATS Abono Mes"
	#define STR0314 "ATS Abono Mes Sig."
	#define STR0315 "ATS Abono Mes s/ Conceptos"
	#define STR0316 "ATS Abono Mes Sig. s/ Conceptos"
	#define STR0317 "Peligrosidad Abono Mes"
	#define STR0318 "Peligrosidad Abono Mes Sig."
	#define STR0319 "Peligrosidad Abono Mes s/ Conceptos"
	#define STR0320 "Peligrosidad Abono Mes Sig. s/ Conceptos"
	#define STR0321 "Insalubridad Abono Mes"
	#define STR0322 "Insalubridad Abono Mes Sig."
	#define STR0323 "Insalubridad Abono Mes s/ Conceptos"
	#define STR0324 "Insalubridad Abono Mes Sig. s/ Conceptos"
	#define STR0325 "Adic. Cargo Confianza Abono Mes"
	#define STR0326 "Adic. Cargo Confianza Abono Mes Sig."
	#define STR0327 "Adic. Transferencia Abono Mes"
	#define STR0328 "Adic. Transferencia Abono Mes Sig."
	#define STR0329 "IR PLR Mes Anterior (Base)"
	#define STR0330 "Redondeo de Anticipo (Remuneracion)"
	#define STR0331 "DSR sobre Promedios Abono"
	#define STR0332 "DSR sobre Promedios Abono Mes Siguiente"
	#define STR0333 "Licencia Premio - Goce"
	#define STR0334 "Licencia Premio - Indemnizacion"
	#define STR0335 "Ejercicio Acumulativo"
	#define STR0336 "Vacaciones Compensatorias"
	#define STR0337 "Subsidio Exento de IRPF"
	#define STR0338 "Guardia Indemnizada"
	#define STR0339 "ATS Maternidad"
	#define STR0340 "Insalubridad Maternidad"
	#define STR0341 "Peligrosidad Maternidad"
	#define STR0342 "Adic. Cargo Confianza Maternidad"
	#define STR0343 "Adic. Transferencia Maternidad"
	#define STR0344 "Aportacion Voluntaria AFC"
	#define STR0345 "Aportacion Voluntaria AFP"
	#define STR0346 "Aportacion Voluntaria que participa en la Retencion Contingente"
	#define STR0347 "Retencion Contingente"
	#define STR0348 "Retencion en la Fuente sin Aportaciones Voluntarias"
	#define STR0349 "Retencion en la Fuente con Aportaciones Voluntarias"
	#define STR0350 "Aux. Enfermedad Profesional"
	#define STR0351 "Enfermedad profesional CNS"
	#define STR0352 "Prorogacion - ATS Maternidad"
	#define STR0353 "Prorrogacion - Insalubridad maternidad"
	#define STR0354 "Prorrogacion - Peligrosidad maternidad"
	#define STR0355 "Prorrogacion - Adic. Cargo confianza maternidad"
	#define STR0356 "Prorrogacion - Adic. Transferencia maternidad"
	#define STR0357 "Aportacion Voluntaria AFP Empresa"
	#define STR0358 "Aporte FSP Solidaridad"
	#define STR0359 "Aporte FSP Subsistencia"
	#define STR0360 "Aporte ESAP"
	#define STR0361 "Aporte MEN"
	#define STR0362 "Valor No Retenido Aportacion Voluntaria"
	#define STR0363 "Valor UPC Adicional"
	#define STR0364 "Devolucion faltas II"
	#define STR0365 "Faltas III"
	#define STR0366 "Faltas IV"
	#define STR0367 "Devolucion faltas III"
	#define STR0368 "Devolucion faltas IV"
	#define STR0369 "Reduccion de Jornada"
	#define STR0370 "Abono Permanencia"
	#define STR0371 "Reductor de Techo"
	#define STR0372 "Ticket cultura (Otros ingresos)"
	#define STR0373 "Ticket Cultura (Descuento)"
	#define STR0374 "Sustituciones"
	#define STR0375 "Prev. Propia Descuento - RPPS"
	#define STR0376 "Subsidio Proporcional CNE"
	#define STR0377 "Total percepción grabada"
	#define STR0378 "Dias Horas Extras Dobles"
	#define STR0379 "Dias Horas Extras Triples"
	#define STR0380 "Vacaciones indemnizadas en nomina"
	#define STR0381 "Adicionales vacaciones indemnizadas en nomina"
	#define STR0382 "Abono permanencia retroactivo"
	#define STR0383 "Prev. Propia Descuento Aguinaldo - RPPS"
	#define STR0384 "Vacaciones Progresivas"
	#define STR0385 "Base Inss Contr. Indiv. Cooperado"
	#define STR0386 "Sueldo Contribucion tras la exencion (Aguinaldo)"
	#define STR0387 "Complemento de ticket canasta - Remuneración"
	#define STR0388 "Complemento de ticket canasta - Descuento"
	#define STR0389 "Complemento de ticket canasta - Empresa"
	#define STR0390 "Complemento de ticket restaurante - Remuneración"
	#define STR0391 "Complemento de ticket restaurante - Descuento"
	#define STR0392 "Complemento de ticket restaurante - Empresa"
	#define STR0393 "Complemento de ticket transporte - Remuneración"
	#define STR0394 "Complemento de ticket transporte - Descuento"
	#define STR0395 "Complemento de ticket transporte - Empresa"
	#define STR0396 "Contribución adicional Senai"
	#define STR0397 "Contribución adicional Senai convenio colectivo"
	#define STR0398 "Reducción salario - PPE"
	#define STR0399 "Abono FAT - PPE"
	#define STR0400 "Dominical adicional"
	#define STR0401 "DSR Saldo Salario"
	#define STR0402 "Provisión de receso"
	#define STR0403 "Corrección provisión receso"
	#define STR0404 "Baja provisión receso"
	#define STR0405 "Baja Prov. Receso Transf"
	#define STR0406 "Baja Prov. Receso rescisión"
	#define STR0407 "Pago Pelig. Sobre promedios Vacaciones mes siguiente"
	#define STR0408 "Pago Insalub. Sobre promedios Vacaciones mes siguiente"
	#define STR0409 "Pago Pelig. Sobre promedios abono"
	#define STR0410 "Pago Insalub. Sobre promedios abono"
	#define STR0411 "Pago Pelig. Sobre promedios abono mes siguiente"
	#define STR0412 "Pago Insalub. Sobre promedios abono mes siguiente"
	#define STR0413 "Neto valores extras"
	#define STR0414 "Devolución INSS (Vacaciones con alícuota superior)."
	#define STR0415 "Autónomo MEI sin INSS"
	#define STR0416 "Subsidio guardería con impuesto a la renta"
	#define STR0417 "Licencia remunerada"
	#define STR0418 "1 Cuota 13 Anticipado mismo mes rescisión"
	#define STR0419 "Dif promedio de horas sobre el abono"
	#define STR0420 "Dif promedio del valor sobre el abono"
	#define STR0421 "Dif promedio de horas sobre el abono mes sig."
	#define STR0422 "Dif promedio valor sobre el abono mes sig."
	#define STR0423 "Reservado"
	#define STR0424 "Valor de licencia por enfermedad pagado por el seguro social"
	#define STR0425 "Adicional de confianza del mes"
	#define STR0426 "Adicional de transferencia del mes"
	#define STR0427 "Insalubridad Gestante"
	#define STR0428 "Receso indemnizado"
	#define STR0429 "Receso proporcional"
	#define STR0430 "Base parte Empresa Diferencia Asist.Médica"
	#define STR0431 "Base parte Empresa Diferencia Asist.Medica Dep/Agreg."
	#define STR0432 "Base parte Empresa Diferencia Asist.Odontológica"
	#define STR0433 "Base parte Empresa Diferencia Asist.Odontológica Dep/Agreg."
	#define STR0434 "Remuneración de socios - Directores no empleados"
	#define STR0435 "Remuneración de socios - Propietarios o socios"
	#define STR0436 "Valor de la licencia por accidente pagado por el seguro social"
	#define STR0437 "Valor de remuneración a la que tendría derecho (Servicio Militar)"
	#define STR0438 "1ª cuota Aguinaldo Asignación por maternidad"
	#define STR0439 "Cuota final aguinaldo Asignación por maternidad"
	#define STR0440 "Total de promedios en valor asignación maternidad"
	#define STR0441 "Total de promedios en horas maternidad"
	#define STR0442 "ATS Aguinaldo. Asignación por maternidad"
	#define STR0443 "ATS Aguinaldo sobre conceptos por maternidad"
	#define STR0444 "Peligrosidad Aguinaldo Asignación por maternidad"
	#define STR0445 "Peligrosidad Aguinaldo sobre conceptos por maternidad"
	#define STR0446 "Insalubridad 13. Asignación por maternidad"
	#define STR0447 "Insalubridad Aguinaldo sobre conceptos por maternidad"
	#define STR0448 "Adicional cargo de confianza Aguinaldo Asignación Maternidad"
	#define STR0449 "Adicional Transferencia Aguinaldo.Asignación por maternidad"
	#define STR0450 "Aguinaldo en la indemnización Rescisión Maternidad"
	#define STR0451 "Promedio Aguinaldo Rescisión Maternidad"
	#define STR0452 "Autónomo cooperado"
	#define STR0453 "Abonos Pagos Mes Anterior"
#else
	#ifdef ENGLISH
		#define STR0001 "Social Security"
		#define STR0002 "Employer Social Security"
		#define STR0003 "Vacation Social Security"
		#define STR0004 "Payroll Deduction of Vacation"
		#define STR0005 "Vacation Bonus"
		#define STR0006 "Rescission of Expired Bonus"
		#define STR0007 "Bonus Hour Average"
		#define STR0008 "Bonus Value Average"
		#define STR0009 "Rescission-Proportional Bonus"
		#define STR0010 If( cPaisLoc == "BOL", "Provision Accrued First Annual", "Utility Retained Provision" )
		#define STR0011 If( cPaisLoc == "BOL", "Provision First Annual", "Utility Provision" )
		#define STR0012 "Vacation Bonus Retained Provision"
		#define STR0013 "Additional Retained Provision Bonus Vacation"
		#define STR0014 "Vacation Bonus Additional Provision"
		#define STR0015 "Vacation Bonus Provision"
		#define STR0016 "Vacation Bonus Low Provision"
		#define STR0017 "Rescission Vacation Bonus Low Provision"
		#define STR0018 "Utility Rounding Revenue"
		#define STR0019 "Seniority Paid in Rescission"
		#define STR0020 "Seniority Interests Paid in Rescission"
		#define STR0021 "Seniority Difference Interests"
		#define STR0022 "Utility Net"
		#define STR0023 "Utility Advance Net"
		#define STR0024 "Utility Low Provision"
		#define STR0025 "Rescission Utility Low Provision"
		#define STR0026 "Retirement Base"
		#define STR0027 "Retirement Interests Base"
		#define STR0028 "Retirement"
		#define STR0029 "Retirement Interests"
		#define STR0030 "Low Additional Provision Vacation Bonus"
		#define STR0031 "Rescission Low Additional Provision Vacation Bonus"
		#define STR0032 "Vacation Rest Days"
		#define STR0033 "Difference of Prizes per Service"
		#define STR0034 "Rescission Retained Compensation "
		#define STR0035 "Paternity Aid"
		#define STR0036 "Remuneration Correction"
		#define STR0037 "Employment National Fund"
		#define STR0038 "Shortage of Provision Advance Balance"
		#define STR0039 "Family Allowance Patronal Contribution Base"
		#define STR0040 "Family Allowance Patronal Contribution Value"
		#define STR0041 "Volunteer Apportion Base"
		#define STR0042 "Labor Ingress Base"
		#define STR0043 "Employment National Fund Base"
		#define STR0044 "Year-end bonus on vacations not taken"
		#define STR0045 "Plus on Proportional Vacation"
		#define STR0046 "Employee Retirement Base Difference"
		#define STR0047 "Employee Social Work Base Difference"
		#define STR0048 "Employee INSSJP Base Difference"
		#define STR0049 "Employee ART Base Difference"
		#define STR0050 "FNE Difference"
		#define STR0051 "Patronal Family Allowance Difference"
		#define STR0052 "Patronal Retirement Base Difference"
		#define STR0053 "Patronal Social Work Base Difference"
		#define STR0054 "Patronal INSSJP Base Difference"
		#define STR0055 "Entire Salary"
		#define STR0056 "Salary discount as to vacation days"
		#define STR0057 "Employee Retirement/INSS Base Year-end Bonus"
		#define STR0058 "Company Retirement/INSS Base Year-end Bonus"
		#define STR0059 "Employee Retirement/INSS Year-end Bonus"
		#define STR0060 "Company Retirement/INSS Year-end Bonus"
		#define STR0061 "Employee Social Work Base Year-end Bonus"
		#define STR0062 "Company Social Work Base Year-end Bonus"
		#define STR0063 "Employee Social Work Year-end Bonus"
		#define STR0064 "Company Social Work Year-end Bonus"
		#define STR0065 "Employee ANSSAL Year-end Bonus"
		#define STR0066 "Company ANSSAL Year-end Bonus"
		#define STR0067 "Year-end Bonus Base InssJP/Ley 19032 Employee"
		#define STR0068 "Year-end Bonus Base InssJP/Ley 19032 Company"
		#define STR0069 "Year-end Bonus InssJP/Ley 19032 Employee"
		#define STR0070 "Year-end Bonus InssJP/Ley 19032 Company"
		#define STR0071 "Employee Social Work DIF. Year-end Bonus"
		#define STR0072 "Company Social Work DIF. Year-end Bonus"
		#define STR0073 "ART Base Year-end Bonus"
		#define STR0074 "Company ART Year-end Bonus"
		#define STR0075 "Primas Exempt Base"
		#define STR0076 "Employee Retirement/INSS Base FER."
		#define STR0077 "Company Retirement/INSS Base FER."
		#define STR0078 "Company Retirement/INSS FER."
		#define STR0079 "Company Social Work DIF. FER."
		#define STR0080 "Company Social Work Base FER."
		#define STR0081 "Company Social Work FER."
		#define STR0082 "Company ANSSAL FER. "
		#define STR0083 "FER. Base InssJP/Ley 19032 Company"
		#define STR0084 "FER. InssJP/Ley 19032 Company"
		#define STR0085 "ART Base FER. "
		#define STR0086 "Company ART FER. "
		#define STR0087 "Discount of Rescission Days"
		#define STR0088 "Company AFP - Absences"
		#define STR0089 "Vacations compensated"
		#define STR0090 "Average of vacations compensated"
		#define STR0091 "Non-working days base"
		#define STR0092 "Rescission compensation"
		#define STR0093 "Foreign/National Cost Aid"
		#define STR0094 "Education Cost Aid"
		#define STR0095 "Disc Vacation Month CVG"
		#define STR0096 "Vacation Base Following Month CVG"
		#define STR0097 "Amount of determined tax"
		#define STR0098 "Amount of determined tax vacation "
		#define STR0099 "Amount of determined tax advance"
		#define STR0100 "Vacation Pay"
		#define STR0101 "Days of vacation not taken in rescission"
		#define STR0102 "Second currency net amt."
		#define STR0103 "FSP Base"
		#define STR0104 "Breach of Contract - Rescission"
		#define STR0105 "Vacation FSP Basis"
		#define STR0106 "Vacation Disc.Advanced Days"
		#define STR0107 "AFP Base"
		#define STR0108 "Vacation AFP Basis"
		#define STR0109 "Total Base Retirement"
		#define STR0110 "Social Work Total Base"
		#define STR0111 "Law Total Base"
		#define STR0112 "ART Total Base"
		#define STR0113 "Additional Contribution AFP Base"
		#define STR0114 "Volunteer Contribution AFP Base"
		#define STR0115 "CFDCT "
		#define STR0116 "OFATMA-Workers Compensation Insurance "
		#define STR0117 "SNP Pension"
		#define STR0118 "Paym. Medical Rest"
		#define STR0119 "IRRF Contribution Base (Other Companies)"
		#define STR0120 "IRRF Discount Base (Other Companies)"
		#define STR0121 "SCRT Base"
		#define STR0122 "SCRT Pension"
		#define STR0123 "SCRT Salud"
		#define STR0124 "SENATI Base"
		#define STR0125 "SENATI"
		#define STR0126 "Company Life Insurance"
		#define STR0127 "Devolução Reliquidação de Ganância"
		#define STR0128 "Withholding Gains Resettleling"
		#define STR0129 "Net Amount Compensation per Service Time"
		#define STR0130 "Compensation per Service Time - Accrued Prev. Semester"
		#define STR0131 "Devolution of settled gains."
		#define STR0132 "Retention of settled gains."
		#define STR0133 "Compensation Base by Time of Service"
		#define STR0134 "Aid Fund / Extraordinary Bonus"
		#define STR0135 "Net Gratification"
		#define STR0136 "Reward Base"
		#define STR0137 "Bonus Difference - Revenue"
		#define STR0138 "Bonus Difference - Discount"
		#define STR0139 "Base Average Vacations Value"
		#define STR0140 "Accrued CTS (Semester)"
		#define STR0141 "Acrrued CTS (Month)"
		#define STR0142 "Accrued Bonus (Semester)"
		#define STR0143 "Accrued Bonus (Month)"
		#define STR0144 "Gratifications Provision Write Off"
		#define STR0145 "Low Provision Compensation per Service Time "
		#define STR0146 "Private Pension System - Prima de Seguros"
		#define STR0147 "Private Pension System - Commission Base"
		#define STR0148 "Private Pension System Base - Prima de Seguros"
		#define STR0149 "AFP Taken"
		#define STR0150 "Utilities - Worked Days"
		#define STR0151 "Utilities Base - Payment"
		#define STR0152 "Utility - Payment"
		#define STR0153 "Average of absences"
		#define STR0154 "Voluntary Apportionment with Provisional End"
		#define STR0155 "Voluntary Apportionment without Provisional End"
		#define STR0156 "IT deduction"
		#define STR0157 "Base Tot Pat Jubilacion"
		#define STR0158 "Base Tot Pat InssJP/Lei 19032"
		#define STR0159 "Total Base Pat.Family Allowance"
		#define STR0160 "Base Tot Pat FNE"
		#define STR0161 "13o.Base Tot Pat Jubilacion"
		#define STR0162 "13o.Base Tot Pat InssJP/Lei 19032"
		#define STR0163 "Total Base Pat.Year-End Bonus"
		#define STR0164 "13o.Base Tot Pat FNE"
		#define STR0165 "FER.Total Base Pat. Retirement"
		#define STR0166 "FER.Base Tot Pat InssJP/Lei 19032"
		#define STR0167 "School auxiliary"
		#define STR0168 "Bonus per Altitude"
		#define STR0169 "Bonus per Height"
		#define STR0170 "Civil Construction Unified Bonus"
		#define STR0171 "Negative Net Tax Base"
		#define STR0172 "Extra shifts - informative"
		#define STR0173 "Conafovicer Base"
		#define STR0174 "Conafovicer"
		#define STR0175 "Vacation Compensation Base"
		#define STR0176 "Vacation Compensation"
		#define STR0177 "Tax Return inAdvance"
		#define STR0178 "Bonus Law No. 29351 - Essalud"
		#define STR0179 "Bonus Law No. 29351 - EPS"
		#define STR0180 "Educational Credit Base"
		#define STR0181 "Educational Credit Value"
		#define STR0182 "Professional Training Base"
		#define STR0183 "Professional Training Value"
		#define STR0184 "Educational Credit Base Vacation"
		#define STR0185 "Educational Credit Value Vacation"
		#define STR0186 "Professional Training Base Vacation"
		#define STR0187 "Professional Training Value Vacation"
		#define STR0188 "Income Tax Other Companies"
		#define STR0189 "Projected IT Base "
		#define STR0190 "Base of Projected Social Security Value"
		#define STR0191 "Additional year-end bonus"
		#define STR0192 "Net Amount 14h Salary"
		#define STR0193 "Water Bonus"
		#define STR0194 "Income Tax Return RG 2867"
		#define STR0195 "Addic. Contribution Const. Civil - Employee"
		#define STR0196 "Addic. Contribution Const. Civil - Company"
		#define STR0197 "Base of Termination Compensation"
		#define STR0198 "Allowance up to the Limit in Portugal (Exempt)"
		#define STR0199 "Allowance above the Limit in Portugal (Taxed)"
		#define STR0200 "Allowance up to the Limit abroad (Exempt)"
		#define STR0201 "Allowance above the Limit abroad (Taxed)"
		#define STR0202 "Value utilities family"
		#define STR0203 "Base 13 Salary in Termination"
		#define STR0204 " Disability Deduction"
		#define STR0205 "Seniority Deduction"
		#define STR0206 "Additional year-end bonus at the termination"
		#define STR0207 "Union Contribution Calculation Base"
		#define STR0208 "Additional days taken"
		#define STR0209 "Untimely Resignation Base"
		#define STR0210 "Untimely Resignation"
		#define STR0211 "Exceeding Employer Contribution Base"
		#define STR0212 "AFP Additional Contribution"
		#define STR0213 "IRS taxable indemnity exceeding value"
		#define STR0214 "Vacation Calculation Base"
		#define STR0215 "Accrued Year-end Bonus (Month)"
		#define STR0216 "Accrued Year-end Bonus (Year)"
		#define STR0217 "Accrued Extra Year-end Bonus (Month)"
		#define STR0218 "Accrued Extra Year-end Bonus (Year)"
		#define STR0219 "Reserve Fund Base"
		#define STR0220 "Reserve Fund"
		#define STR0221 "Reserve Fund - IESS"
		#define STR0222 "Days Worked for Utilities"
		#define STR0223 "Days Worked Loads for Utilities"
		#define STR0224 "Tax Return RG 2867 Vacation "
		#define STR0225 "Reserve Fund Base - Vacation"
		#define STR0226 "Reserve Fund - Vacation"
		#define STR0227 "IESS Reserve Fund - Vacation"
		#define STR0228 "Base AFP Solidary Apportionment"
		#define STR0229 "AFP Solidary Apportionment"
		#define STR0230 "Vacations Full Base "
		#define STR0231 "Vacations Proportional Base"
		#define STR0232 "Dev .Vac. Tax"
		#define STR0233 "Seniority Interest Payment"
		#define STR0234 "Compensation Base - Early Contract Termination"
		#define STR0235 "Compensation Amount - Early Contract Termination"
		#define STR0236 "Dev. Prepaid Healthcare - Employee"
		#define STR0237 "Dev. Prepaid Healthcare - Company"
		#define STR0238 "sunday absence"
		#define STR0239 "Compensation Provision Write Off "
		#define STR0240 "Maternity Allowance Extension"
		#define STR0241 "Maternity Allowance Extension averages payment"
		#define STR0242 "Paid Vacations"
		#define STR0243 "Cesantia Provision Write-off"
		#define STR0244 "Cesantia Interest Provision Write-off"
		#define STR0245 "Primas Provision Write-off"
		#define STR0246 "Compensation for Pregnancy"
		#define STR0247 "Additional UPC "
		#define STR0248 "Fundo Solidário Total Base"
		#define STR0249 "Social Work Bonus - Employee"
		#define STR0250 "ANSSAL Bonus - Employee"
		#define STR0251 "Social Work Bonus - Employer"
		#define STR0252 "ANSSAL Bonus - Employer"
		#define STR0253 "Social Work Bonus Vacations - Employee"
		#define STR0254 "ANSSAL Bonus Vacations - Employee"
		#define STR0255 "Social Work Bonus Vacations - Employer"
		#define STR0256 "ANSSAL Bonus Vacations - Employer"
		#define STR0257 "Social Work Bonus SAC - Employee"
		#define STR0258 "ANSSAL Bonus SAC - Employee"
		#define STR0259 "Social Work Bonus SAC - Employer"
		#define STR0260 "ANSSAL Bonus SAC - Employer"
		#define STR0261 "Social Work Dif. Base Vacations"
		#define STR0262 "Dif. Dev. Health Plan"
		#define STR0263 "Earnings Base Value Vacations"
		#define STR0264 "BS Social Work Bonus Vacations - Employee"
		#define STR0265 "BS ANSSAL Bonus Vacations - Employee"
		#define STR0266 "Return of Paid SAC to Employee"
		#define STR0267 "Extra Bonus"
		#define STR0268 "Extra Bonus - Difference"
		#define STR0269 "Bonus Quota Zero"
		#define STR0270 "Extra Bonus in Termination"
		#define STR0271 "Infotep Utilities"
		#define STR0272 "Infotep Payroll"
		#define STR0273 "Base Salary for Leaves (Maternity, Disease and Insurance Allowance)"
		#define STR0274 "Five-year Base Salary"
		#define STR0275 "Five years by Script"
		#define STR0276 "Five years expired"
		#define STR0277 "Border Subsidy"
		#define STR0278 "Deduction per Dependant"
		#define STR0279 "xxxxxxxxxxxxxxxxxxxxxxxxxxxxx"
		#define STR0280 "Distribution of Profit 1st Installment (Discount)"
		#define STR0281 "Maternity Allow. Ded."
		#define STR0282 "Hazard on funds"
		#define STR0283 "Insalubrity on funds"
		#define STR0284 "One-Year Bonus on funds"
		#define STR0285 "Two-Year Bonus on funds"
		#define STR0286 "Three-Year Bonus on funds"
		#define STR0287 "Four-Year Bonus on funds"
		#define STR0288 "Five-Year Bonus on funds"
		#define STR0289 "13th Salary ATS"
		#define STR0290 "13th Salary ATS on funds"
		#define STR0291 "13th Salary Hazard"
		#define STR0292 "13th Salary Hazard on funds"
		#define STR0293 "13th Salary Insalubrity "
		#define STR0294 "13th Salary Insalubrity on funds"
		#define STR0295 "13th Salary Position of Trust Additional"
		#define STR0296 "13th Salary Transfer Additional"
		#define STR0297 "ATS Vacation Month"
		#define STR0298 "ATS Vacation Following Month"
		#define STR0299 "ATS Vacation Month without Payroll Items"
		#define STR0300 "ATS Vacation Following Month without Payroll Items"
		#define STR0301 "Vacation Hazard Month"
		#define STR0302 "Vacation Hazard Following Month"
		#define STR0303 "Hazard Vacation Month without Payroll Items"
		#define STR0304 "Hazard Vacation Following Month without Payroll Items"
		#define STR0305 "Insalubrity Vacation Month"
		#define STR0306 "Insalubrity Vacation Following Month"
		#define STR0307 "Insalubrity Vacation Month without Payroll Items"
		#define STR0308 "Insalubrity Vacation Following Month without Payroll Items"
		#define STR0309 "Add. Position of Trust Vacation Month"
		#define STR0310 "Add. Position of Trust Vacation Following Month"
		#define STR0311 "Add. Transfer Vacation Month"
		#define STR0312 "Add. Transfer Vacation Following Month"
		#define STR0313 "ATS Bonus Month"
		#define STR0314 "ATS Abono Mês Seg."
		#define STR0315 "ATS Bonus Month without Payroll Items"
		#define STR0316 "ATS Bonus Following Month without Payroll Items"
		#define STR0317 "Hazard Bonus Month"
		#define STR0318 "Hazard Following Month"
		#define STR0319 "Hazard Bonus Month without Payroll Items"
		#define STR0320 "Hazard Bonus Following Month without Payroll Items"
		#define STR0321 "Insalubrity Bonus Month"
		#define STR0322 "Insalubrity Bonus Following Month"
		#define STR0323 "Insalubrity Bonus Month without Payroll Items"
		#define STR0324 "Insalubrity Bonus Following Month without Payroll Items"
		#define STR0325 "Add. Position of Trust Bonus Month"
		#define STR0326 "Add. Position of Trust Bonus Following Month"
		#define STR0327 "Add. Transfer Bonus Month"
		#define STR0328 "Add. Transfer Bonus Following Month"
		#define STR0329 "IR PLR Previous Month (Base)"
		#define STR0330 "Adv Rounding (Provision)"
		#define STR0331 "PWR on Bonus Average"
		#define STR0332 "PWR on Bonus Average Following Month"
		#define STR0333 "Bonus Leave - Celebrating"
		#define STR0334 "Bonus Leave - Indemnification"
		#define STR0335 "Cumulative Exercise"
		#define STR0336 "Compensatory Vacation"
		#define STR0337 "Subsidy Exempt IRPF"
		#define STR0338 "Indemnified Shift"
		#define STR0339 "Maternity ATS"
		#define STR0340 "Maternity Insalubrity"
		#define STR0341 "Maternity Hazardousness"
		#define STR0342 "Add Maternity Trust Position"
		#define STR0343 "Add Maternity Transfer"
		#define STR0344 "AFC Volunteer Contribution"
		#define STR0345 "AFP Volunteer Contribution"
		#define STR0346 "Volunteer contribution that participates in the contingent withholding"
		#define STR0347 "Contingent Withholding"
		#define STR0348 "Withholding at source without volunteer contributions"
		#define STR0349 "Withholding at source with volunteer contributions"
		#define STR0350 "Comp. Professional Infirmity"
		#define STR0351 "CNS professional infirmity"
		#define STR0352 "Postponement - Maternity ATS"
		#define STR0353 "Postponement - Maternity Unhealthiness"
		#define STR0354 "Postponement - Maternity Health Hazard"
		#define STR0355 "Postponement - Addit. Maternity Trust Position"
		#define STR0356 "Postponement - Addit. Maternity Transfer"
		#define STR0357 "Company AFP Volunteer Contribution"
		#define STR0358 "Solidarity FSP Contribution"
		#define STR0359 "Solidarity FSP Subsistence"
		#define STR0360 "ESAP Contribution"
		#define STR0361 "MEN Contribution"
		#define STR0362 "Value not Withheld Volunteer Contribution"
		#define STR0363 "Additional UPC Value"
		#define STR0364 "Devolução Faltas II"
		#define STR0365 "Absence III"
		#define STR0366 "Absence IV"
		#define STR0367 "Absence Return III"
		#define STR0368 "Absence Return IV"
		#define STR0369 "Working Hours Reduction"
		#define STR0370 "Permanence Bonus"
		#define STR0371 "Ceiling Reduction"
		#define STR0372 "Culture Voucher (Revenue)"
		#define STR0373 "Culture Voucher (Discount)"
		#define STR0374 "Substitutions"
		#define STR0375 "Prev. Own Discount - RPPS"
		#define STR0376 "CNE Proportional Subsidy"
		#define STR0377 "xxxxxxxxxxxxxxxxxx"
		#define STR0378 "Days Overtime Dobles"
		#define STR0379 "Days Overtime Triples"
		#define STR0380 "Vacation Compensated in Payroll"
		#define STR0381 "Vacation Additional Compensated in Payroll"
		#define STR0382 "Retroactive Permanence Bonus"
		#define STR0383 "Prev. Own Discount Year-end Bonus - RPPS"
		#define STR0384 "Vacaciones Progresivas"
		#define STR0385 "Base Inss Contr. Indiv. Cooperaded"
		#define STR0386 "Contribution Salary After Release (Year-End Bonus)"
		#define STR0387 "Food Allowance Complement - Provision"
		#define STR0388 "Food Allowance Complement - Discount"
		#define STR0389 "Food Allowance Complement - Company"
		#define STR0390 "Meal Voucher Complement - Provision"
		#define STR0391 "Meal Voucher Complement - Discount"
		#define STR0392 "Meal Voucher Complement - Company"
		#define STR0393 "Transportation Allowance Complement - Provision"
		#define STR0394 "Transportation Allowance Complement - Discount"
		#define STR0395 "Transportation Allowance Complement - Company"
		#define STR0396 "Senai Additional Contribution"
		#define STR0397 "Senai Additional Contribution Labor Agreement"
		#define STR0398 "Remuneration Reduction - PPE"
		#define STR0399 "FAT Bonus - PPE"
		#define STR0400 "Additional Sunday"
		#define STR0401 "PWR Salary Balance"
		#define STR0402 "Recess Provision"
		#define STR0403 "Recess Provision Correction"
		#define STR0404 "Recess Provision Write-off"
		#define STR0405 "Transf Recess Prov. Write-off"
		#define STR0406 "Termination Recess Prov. Write-off"
		#define STR0407 "Danger Paymt Vacation Averages Following Month"
		#define STR0408 "Insalub. Paymt Vacation Averages Following Month"
		#define STR0409 "Danger Paymt on Bonus Averages"
		#define STR0410 "Insalub. Paymt on Bonus Averages"
		#define STR0411 "Danger Paymt Bonus Averages Following Month"
		#define STR0412 "Insalub. Paymt Bonus Averages Following Month"
		#define STR0413 "Net Bonus Amounts"
		#define STR0414 "Inss return (vacation with higher rate)"
		#define STR0415 "Freelancer MEI without INSS"
		#define STR0416 "Day Care Center Ais with Income Tax"
		#define STR0417 "Paid leave"
		#define STR0418 "1 Instal. advanced bonus same month dismissal"
		#define STR0419 "Dif hour average on waiver"
		#define STR0420 "Dif value average on waiver"
		#define STR0421 "Dif hour average on waiver fol month"
		#define STR0422 "Dif value average on waiver fol month"
		#define STR0423 "Reserved"
		#define STR0424 "Value of disease-related leave paid by Social Security"
		#define STR0425 "Trust Bonus of the Month"
		#define STR0426 "Transfer Bonus of the Month"
		#define STR0427 "Pregnant Women Insalubrity"
		#define STR0428 "Compensated Recess"
		#define STR0429 "Proportional Recess"
		#define STR0430 "Base part Company Difference Medical Care Plan"
		#define STR0431 "Base part Company Difference Medical Care Plan Dep/Household Member"
		#define STR0432 "Base part Company Difference Dental Plan"
		#define STR0433 "Base part Company Difference Dental Plan Dep/Household Member"
		#define STR0434 "Pro-Labore - Directors not employed"
		#define STR0435 "Pro-Labore - Owners or partnerships"
		#define STR0436 "Value of accident-related leave paid by Social Security"
		#define STR0437 "Value of entitled compensation (Military Service)"
		#define STR0438 "1st Installment. End-of-year bonus Maternity"
		#define STR0439 "Final Installment of Maternity Leave13 Sal"
		#define STR0440 "Total of Averages in Maternity Leave"
		#define STR0441 "Total of Averages in Maternity Hours"
		#define STR0442 "ATS 13 Sal Maternity"
		#define STR0443 "ATS 13 Sal on Maternity funds"
		#define STR0444 "Hazardousness 13 Sal Maternity"
		#define STR0445 "Hazardousness 13 Sal on Maternity funds"
		#define STR0446 "Insalubrity 13 Salary Insalubrity"
		#define STR0447 "Insalubrity 13 Sal on Maternity funds"
		#define STR0448 "13 Salary Position of Trust Additional"
		#define STR0449 "13 Maternity Salary Additional Transfer"
		#define STR0450 "13 in Maternity Termination Compensation"
		#define STR0451 "Average 13 Maternity Termination Salary"
		#define STR0452 "Autonomo cooperado"
		#define STR0453 "Abonos Pagos Mes Anterior"
	#else
		#define STR0001 "Seguro Social"
		#define STR0002 If( cPaisLoc $ "ANG|PTG", "Segurança Social Empregador", "Seguro Social Empregador" )
		#define STR0003 If( cPaisLoc $ "ANG|PTG", "Segurança Social Férias", "Seguro Social Férias" )
		#define STR0004 "Desconto de Férias em Folha"
		#define STR0005 "Bonificação de Férias"
		#define STR0006 "Bonificação Vencida Rescisão"
		#define STR0007 "Média Horas Bonificação"
		#define STR0008 "Média Valor Bonificação"
		#define STR0009 "Bonificação Proporcional Rescisão"
		#define STR0010 If( cPaisLoc == "BOL", "Provisão Acumulada Prima Anual", "Provisão Acumulada Utilidade" )
		#define STR0011 If( cPaisLoc == "BOL", "Provisão Prima Anual", "Provisão Utilidade" )
		#define STR0012 "Provisão Acumulada Bonificação Férias"
		#define STR0013 "Provisão Acumulada Adic. Bonif. Férias"
		#define STR0014 "Provisão Adicional Bonificação Férias"
		#define STR0015 "Provisão Bonificação Férias"
		#define STR0016 If( cPaisLoc $ "ANG|PTG", "Liquidação Provisão Bonificação Férias", "Baixa Provisão Bonificação Férias" )
		#define STR0017 If( cPaisLoc $ "ANG|PTG", "Liquidação Provisão Bonificação Férias Rescisão", "Baixa Provisão Bonificação Férias Rescisão" )
		#define STR0018 "Provento Arredondamento Utilidade"
		#define STR0019 "Antiguidade Paga na Rescisão"
		#define STR0020 "Juros Antiguidade Paga na Rescisão"
		#define STR0021 "Juros Diferença Antiguidade"
		#define STR0022 "Líquido Utilidade"
		#define STR0023 "Líquido Antecipação Utilidade"
		#define STR0024 If( cPaisLoc $ "ANG|PTG", "Liquidação Provisão Utilidade", "Baixa Provisão Utilidade" )
		#define STR0025 If( cPaisLoc $ "ANG|PTG", "Liquidação Provisão Utilidade Rescisão", "Baixa Provisão Utilidade Rescisão" )
		#define STR0026 "Base Cesantia"
		#define STR0027 If( cPaisLoc $ "ANG|PTG", "Base Interesses de Cesantia", "Base Intereses de Cesantia" )
		#define STR0028 "Cesantia"
		#define STR0029 "Intereses de Cesantia"
		#define STR0030 If( cPaisLoc $ "ANG|PTG", "Liquidação Provisão Adicional Bonificação de Férias", "Baixa Provisão Adicional Bonificação de Férias" )
		#define STR0031 If( cPaisLoc $ "ANG|PTG", "Liquidação Provisão Adicional Bonificação de Férias Rescisão", "Baixa Provisão Adicional Bonificação de Férias Rescisão" )
		#define STR0032 "Dias de Repouso nas Férias"
		#define STR0033 "Diferença de Prêmios por Serviços"
		#define STR0034 If( cPaisLoc $ "ANG|PTG", "Acumulado de Indemnização de Rescisão", "Acumulado de Indenização de Rescisão" )
		#define STR0035 If( cPaisLoc $ "ANG|PTG", "Auxílio Paternidade", "Auxilio Paternidade" )
		#define STR0036 If( cPaisLoc $ "ANG|PTG", "Rectificação de Remuneração", "Retificação de Remuneração" )
		#define STR0037 "Fundo Nacional de Emprego"
		#define STR0038 "Insuficiência de Saldo Adiantamento Provisão"
		#define STR0039 If( cPaisLoc $ "ANG|PTG", "Base Contribuição Patronal Salário Família", "Base Contribuicao Patronal Salario Familia" )
		#define STR0040 If( cPaisLoc $ "ANG|PTG", "Valor Contribuição Patronal Salário Família", "Valor Contribuicao Patronal Salario Familia" )
		#define STR0041 If( cPaisLoc $ "ANG|PTG", "Base Aportes Voluntários", "Base Aportes Voluntarios" )
		#define STR0042 "Base Ingressos Laborales"
		#define STR0043 "Base Fundo Nacional de Emprego"
		#define STR0044 If( cPaisLoc $ "ANG|PTG", "Subsídio de Natal sobre Férias Não Gozadas", "13o Salario sobre Ferias Nao Gozadas" )
		#define STR0045 If( cPaisLoc $ "ANG|PTG", "Plus sobre Férias Proporcionais", "Plus sobre Ferias Proporcionais" )
		#define STR0046 If( cPaisLoc $ "ANG|PTG", "Diferença Base Jubilacion Empregado", "Diferença Base Jubilacion Funcionario" )
		#define STR0047 If( cPaisLoc $ "ANG|PTG", "Diferença Base Obra Social Empregado", "Diferença Base Obra Social Funcionario" )
		#define STR0048 If( cPaisLoc $ "ANG|PTG", "Diferença Base INSSJP Empregado", "Diferença Base INSSJP Funcionario" )
		#define STR0049 If( cPaisLoc $ "ANG|PTG", "Diferença Base ART Empregado", "Diferença Base ART Funcionario" )
		#define STR0050 "Diferença FNE"
		#define STR0051 If( cPaisLoc $ "ANG|PTG", "Diferença Salário Família Patronal", "Diferença Salario Familia Patronal" )
		#define STR0052 "Diferença Base Jubilacion Patronal"
		#define STR0053 "Diferença Base Obra Social Patronal"
		#define STR0054 "Diferença Base INSSJP Patronal"
		#define STR0055 If( cPaisLoc $ "ANG|PTG", "Salário Integral", "Salario Integral" )
		#define STR0056 "Desconto de Dias de Férias do Salário"
		#define STR0057 If( cPaisLoc $ "ANG|PTG", "13o.Base Inss/Jubilacion Empregado", "13o.Base Inss/Jubilacion Funcionario" )
		#define STR0058 "13o.Base Inss/Jubilacion Empresa"
		#define STR0059 "13o.Inss/Jubilacion Funcionario"
		#define STR0060 "13o.Inss/Jubilacion Empresa"
		#define STR0061 If( cPaisLoc $ "ANG|PTG", "Subs.Natal Base Obra Social Empregado", "13o.Base Obra Social Funcionario" )
		#define STR0062 If( cPaisLoc $ "ANG|PTG", "Subs.Natal.Base Obra Social Empresa", "13o.Base Obra Social Empresa" )
		#define STR0063 If( cPaisLoc $ "ANG|PTG", "Subs.Natal.Obra Social Empregado", "13o.Obra Social Funcionario" )
		#define STR0064 If( cPaisLoc $ "ANG|PTG", "Subs.Natal. Obra Social Empresa", "13o.Obra Social Empresa" )
		#define STR0065 If( cPaisLoc $ "ANG|PTG", "Subs.natal. ANSSAL Empregado", "13o.ANSSAL Funcionario" )
		#define STR0066 If( cPaisLoc $ "ANG|PTG", "Subs.Natal. ANSSAL Empresa", "13o.ANSSAL Empresa" )
		#define STR0067 If( cPaisLoc $ "ANG|PTG", "13o.Base InssJP/Ley 19032 Empregado", "13o.Base InssJP/Ley 19032 Funcionario" )
		#define STR0068 "13o.Base InssJP/Ley 19032 Empresa"
		#define STR0069 If( cPaisLoc $ "ANG|PTG", "13o.InssJP/Ley 19032 Empregado", "13o.InssJP/Ley 19032 Funcionario" )
		#define STR0070 "13o.InssJP/Ley 19032 Empresa"
		#define STR0071 If( cPaisLoc $ "ANG|PTG", "Subsídio de Natal DIF.Obra Social Empregado", "13o.DIF.Obra Social Funcionario" )
		#define STR0072 If( cPaisLoc $ "ANG|PTG", "Subsídio de Natal DIF.Obra Social Empresa", "13o.DIF.Obra Social Empresa" )
		#define STR0073 If( cPaisLoc $ "ANG|PTG", "Subsídio de Natal Base ART", "13o.Base ART" )
		#define STR0074 If( cPaisLoc $ "ANG|PTG", "Subsídio de Natal ART Empresa", "13o.ART Empresa" )
		#define STR0075 "Base Isenta Primas"
		#define STR0076 If( cPaisLoc $ "ANG|PTG", "FER.Base Inss/Jubilacion Empregado", "FER.Base Inss/Jubilacion Funcionario" )
		#define STR0077 "FER.Base Inss/Jubilacion Empresa"
		#define STR0078 "FER.Inss/Jubilacion Empresa"
		#define STR0079 "FER.DIF.Obra Social Empresa"
		#define STR0080 "FER.Base Obra Social Empresa"
		#define STR0081 "FER.Obra Social Empresa"
		#define STR0082 "FER.ANSSAL Empresa"
		#define STR0083 "FER.Base InssJP/Ley 19032 Empresa"
		#define STR0084 "FER.InssJP/Ley 19032 Empresa"
		#define STR0085 "FER.Base ART"
		#define STR0086 "FER.ART Empresa"
		#define STR0087 If( cPaisLoc $ "ANG|PTG", "Desconto de Dias Rescisão", "Desconto de Dias Rescisao" )
		#define STR0088 If( cPaisLoc $ "ANG|PTG", "AFP Empresa - Ausências", "AFP Empresa - Ausencias" )
		#define STR0089 If( cPaisLoc $ "ANG|PTG", "Férias Compensadas", "Ferias Compensadas" )
		#define STR0090 If( cPaisLoc $ "ANG|PTG", "Média de Férias Compensadas", "Media de Ferias Compensadas" )
		#define STR0091 If( cPaisLoc $ "ANG|PTG", "Base Dias Não Úteis", "Base Dias Nao Uteis" )
		#define STR0092 If( cPaisLoc $ "ANG|PTG", "Compensação na Rescisão", "Compensacao na Rescisao" )
		#define STR0093 If( cPaisLoc $ "ANG|PTG", "Ajuda de Custo Nac./ Estrang.", "Ajuda de Custo Nac / Estrang" )
		#define STR0094 If( cPaisLoc $ "ANG|PTG", "Ajuda de Custo Formação", "Ajuda de Custo Formacao" )
		#define STR0095 If( cPaisLoc $ "ANG|PTG", "Desc.Férias Mês CVG", "Desc Ferias Mes CVG" )
		#define STR0096 If( cPaisLoc $ "ANG|PTG", "Base Férias Mês Seguinte CVG", "Base Ferias Mes Seguinte CVG" )
		#define STR0097 "Valor do Imposto Determinado"
		#define STR0098 If( cPaisLoc $ "ANG|PTG", "Valor Imposto determinado férias", "Valor Imposto determinado vacaciones" )
		#define STR0099 "Valor Imposto determinado adiantamento"
		#define STR0100 If( cPaisLoc $ "ANG|PTG", "Remuneração de férias", "Remuneração de Ferias" )
		#define STR0101 "Dias de Férias Não Gozadas na Rescisão"
		#define STR0102 "Líquido Segunda Moeda"
		#define STR0103 "Base FSP"
		#define STR0104 "Quebra de Contrato - Rescisão"
		#define STR0105 "Base FSP Vacaciones"
		#define STR0106 If( cPaisLoc $ "ANG|PTG", "Desc.Dias Antecipados em Férias", "Desc.Dias Antecipados em Ferias" )
		#define STR0107 "Base AFP"
		#define STR0108 "Base AFP Vacaciones"
		#define STR0109 If( cPaisLoc $ "ANG|PTG", "Base Total Reforma", "Base Total Aposentadoria" )
		#define STR0110 "Base Total Obra Social"
		#define STR0111 "Base Total Lei"
		#define STR0112 "Base Total ART"
		#define STR0113 If( cPaisLoc $ "ANG|PTG", "Base AFP Contribuição Adicional", "Base AFP Contribuicao Adicional" )
		#define STR0114 If( cPaisLoc $ "ANG|PTG", "Base AFP Contribuição Voluntária", "Base AFP Contribuicao Voluntaria" )
		#define STR0115 "CFDCT "
		#define STR0116 "OFATMA-Seguro Contra Acidente Trabalho "
		#define STR0117 If( cPaisLoc $ "ANG|PTG", "Pensão SNP", "Pensao SNP" )
		#define STR0118 If( cPaisLoc $ "ANG|PTG", "Pgt.Descanso Médico", "Pagto.Descanso Medico" )
		#define STR0119 If( cPaisLoc $ "ANG|PTG", "Base Contribuição de IRS (Outras Empresas)", "Base Contribuicao de IRRF (Outras Empresas)" )
		#define STR0120 If( cPaisLoc $ "ANG|PTG", "Base de cálculo para Adiantamento", "Base de calculo para Adiantamento" )
		#define STR0121 "Base SCRT"
		#define STR0122 If( cPaisLoc $ "ANG|PTG", "SCRT Pensão", "SCRT Pensao" )
		#define STR0123 "SCRT Salud"
		#define STR0124 "Base SENATI"
		#define STR0125 "SENATI"
		#define STR0126 "Seguro de Vida Empresa"
		#define STR0127 "Devolução Reliquidação de Ganância"
		#define STR0128 "Retenção Reliquidação de Ganância"
		#define STR0129 "Líquido Compensação por Tempo de Serviço"
		#define STR0130 "Compensação por Tempo de Serviço - Acumulado Semestre Ant."
		#define STR0131 "Devolução de ganância já liquidada."
		#define STR0132 "Retenção de ganância já liquidada."
		#define STR0133 If( cPaisLoc $ "ANG|PTG", "Base Compensação por Tempo de Serviço", "Base Compensação por Tempo de Servico" )
		#define STR0134 "Fundo de Ajuda / Gratificação Extraordinária"
		#define STR0135 "Liquido Gratificacion"
		#define STR0136 If( cPaisLoc $ "ANG|PTG", "Base Gratificação", "Base Gratificacao" )
		#define STR0137 If( cPaisLoc $ "ANG|PTG", "Diferença Gratificação - ~Remuneração", "Diferença Gratificação - Provento" )
		#define STR0138 "Diferença Gratificação - Desconto"
		#define STR0139 If( cPaisLoc $ "ANG|PTG", "Base Média Férias Valor", "Base Media Ferias Valor" )
		#define STR0140 "Acumulado CTS (Semestre)"
		#define STR0141 "Acumulado CTS (Mês)"
		#define STR0142 "Acumulado Gratificações (Semestre)"
		#define STR0143 "Acumulado Gratificações (Mês)"
		#define STR0144 If( cPaisLoc $ "ANG|PTG", "Liquidação Provisão Gratificações", "Baixa Provisão Gratificações" )
		#define STR0145 If( cPaisLoc $ "ANG|PTG", "Liquidação Provisão Compensação por Tempo de Serviço", "Baixa Provisão Compensação por Tempo de Serviço" )
		#define STR0146 "Sistema Privado de Pensão - Prima de Seguros"
		#define STR0147 "Sistema Privado de Pensão - Comissão Base"
		#define STR0148 "Base Sistema Privado de Pensão - Prima de Seguros"
		#define STR0149 "AFP Assumido"
		#define STR0150 "Utilidades - Dias Trabalhados"
		#define STR0151 "Base Utilidades - Remuneração"
		#define STR0152 "Utilidades - Remuneração"
		#define STR0153 If( cPaisLoc $ "ANG|PTG", "Média de Afastamentos", "Media de Afastamentos" )
		#define STR0154 "Aporte Voluntário com Fim Provisional"
		#define STR0155 "Aporte Voluntário sem Fim Provisional"
		#define STR0156 "Dedução IR"
		#define STR0157 "Base Tot Pat Jubilacion"
		#define STR0158 If( cPaisLoc $ "ANG|PTG", "Base Tot.Pat.InssJP/Lei 19032", "Base Tot Pat InssJP/Lei 19032" )
		#define STR0159 If( cPaisLoc $ "ANG|PTG", "Base Tot.Remun.Família Pat.", "Base Tot Salário Família Pat." )
		#define STR0160 If( cPaisLoc $ "ANG|PTG", "Base Tot.Pat.FNE", "Base Tot Pat FNE" )
		#define STR0161 If( cPaisLoc $ "ANG|PTG", "Subs. Natal Base Tot.Pat.Jubilacion", "13o.Base Tot Pat Jubilacion" )
		#define STR0162 If( cPaisLoc $ "ANG|PTG", "Subs. Natal Base Tot.Pat.INSSJP/Lei 19032", "13o.Base Tot Pat InssJP/Lei 19032" )
		#define STR0163 If( cPaisLoc $ "ANG|PTG", "Subs. Natal Base Tot.Remun. Família Pat.", "13o. Base Tot Salário Família Pat." )
		#define STR0164 If( cPaisLoc $ "ANG|PTG", "Sub. Natal Base Tot Pat FNE", "13o.Base Tot Pat FNE" )
		#define STR0165 If( cPaisLoc $ "ANG|PTG", "FÉR.Base Tot Aposentadoria Pat", "FER.Base Tot Aposentadoria Pat" )
		#define STR0166 "FER.Base Tot Pat InssJP/Lei 19032"
		#define STR0167 If( cPaisLoc $ "ANG|PTG", "Auxílio Escolar", "Auxilio Escolar" )
		#define STR0168 "Bonificação por Altitude"
		#define STR0169 "Bonificação por Altura"
		#define STR0170 "Bonificação Unificada de Construção Civil"
		#define STR0171 "Base de Imposto Líquido Negativo"
		#define STR0172 "Horas extras - informativo"
		#define STR0173 "Base Conafovicer"
		#define STR0174 "Conafovicer"
		#define STR0175 "Base Compensação Férias"
		#define STR0176 "Compensação Férias"
		#define STR0177 "Devolução Imposto no Adiantamento"
		#define STR0178 "Bonificação Lei Nº 29351 - Essalud"
		#define STR0179 "Bonificação Lei Nº 29351 - EPS"
		#define STR0180 "Base Crédito Educativo"
		#define STR0181 "Valor Crédito Educativo"
		#define STR0182 "Base Capacitação Profissional"
		#define STR0183 "Valor Capacitação Profissional"
		#define STR0184 "Base Crédito Educativo Férias"
		#define STR0185 "Valor Crédito Educativo Férias"
		#define STR0186 "Base Capacitação Profissional Férias"
		#define STR0187 "Valor Capacitação Profissional Férias"
		#define STR0188 "Imposto de Renda Outras Empresas"
		#define STR0189 If( cPaisLoc $ "ANG|PTG", "Base IR Projectada ", "Base IR Projetada " )
		#define STR0190 If( cPaisLoc $ "ANG|PTG", "Base Valor Seg. Social Projectado", "Base Valor Seg. Social Projetado" )
		#define STR0191 If( cPaisLoc $ "ANG|PTG", "Décimo Quarto Salário", "Decimo Quarto Salario" )
		#define STR0192 If( cPaisLoc $ "ANG|PTG", "Líquido Décimo Quarto Salário", "Liquido Decimo Quarto Salario" )
		#define STR0193 "Bonificação Água"
		#define STR0194 "Devolução Imposto RG 2867"
		#define STR0195 If( cPaisLoc $ "ANG|PTG", "Aporte Adic. Const. Civil - Empregado", "Aporte Adic. Const. Civil - Funcionário" )
		#define STR0196 "Aporte Adic. Const. Civil - Empresa"
		#define STR0197 "Base Indenização Rescisão"
		#define STR0198 If( cPaisLoc $ "ANG|PTG", "Ajuda de custo até o limite em Portugal (Isento)", "Ajuda de custo ate o Limite em Portugal (Isento)" )
		#define STR0199 If( cPaisLoc $ "ANG|PTG", "Ajuda de custo acima do limite em Portugal (Tributado)", "Ajuda de custo acima do Limite em Portugal (Tributado)" )
		#define STR0200 If( cPaisLoc $ "ANG|PTG", "Ajuda de custo até o limite no estrangeiro (Isento)", "Ajuda de custo ate o Limite no estrangeiro (Isento)" )
		#define STR0201 If( cPaisLoc $ "ANG|PTG", "Ajuda de custo acima do limite no estrangeiro (Tributado)", "Ajuda de custo acima do Limite no estrangeiro (Tributado)" )
		#define STR0202 "Valor utilidades familia"
		#define STR0203 If( cPaisLoc $ "ANG|PTG", "Base Subsídio Natal na Rescisão", "Base 13 Salário na Rescisão" )
		#define STR0204 " Dedução Descapacitado"
		#define STR0205 "Dedução 3a. Idade"
		#define STR0206 If( cPaisLoc $ "ANG|PTG", "2o. Subsídio de Natal na Rescisão", "14 Salário na Rescisão" )
		#define STR0207 "Base de Cálculo de Contribuição Sindical"
		#define STR0208 "Dias adicionais gozados"
		#define STR0209 "Base Demissão Inoportuna"
		#define STR0210 "Demissão Inoportuna"
		#define STR0211 If( cPaisLoc $ "ANG|PTG", "Base Contrib. Patronal Excedente", "Base Contrib Patronal Excedente" )
		#define STR0212 If( cPaisLoc $ "ANG|PTG", "Contribuição Adicional AFP", "Contribuicao Adicional AFP" )
		#define STR0213 "Valor excedente de indenização tributável de IRS"
		#define STR0214 If( cPaisLoc $ "ANG|PTG", "Base de cálculo para férias", "Base de Cálculo para Férias" )
		#define STR0215 If( cPaisLoc $ "ANG|PTG", "Acumulado Subsídio de Natal (Mês)", "Acumulado 13 Salário (Mês)" )
		#define STR0216 If( cPaisLoc $ "ANG|PTG", "Acumulado Subsídio de Natal (Ano)", "Acumulado 13 Salário (Ano)" )
		#define STR0217 If( cPaisLoc $ "ANG|PTG", "Acumulado 2o.Subsídio de Natal (Mês)", "Acumulado 14 Salário (Mês)" )
		#define STR0218 If( cPaisLoc $ "ANG|PTG", "Acumulado 2o.Subsídio de Natal (Ano)", "Acumulado 14 Salário (Ano)" )
		#define STR0219 "Base Fundo de Reserva"
		#define STR0220 "Fundo de Reserva"
		#define STR0221 "Fundo de Reserva - IESS"
		#define STR0222 If( cPaisLoc $ "ANG|PTG", "Dias trabalhados p/ utilidades", "Dias Trabalhados p/ Utilidades" )
		#define STR0223 If( cPaisLoc $ "ANG|PTG", "Dias trabalhados cargas p/ utilidades", "Dias Trabalhados Cargas p/ Utilidades" )
		#define STR0224 "Dev. Imposto RG 2867 Fér. "
		#define STR0225 "Base Fundo de Reserva - Férias"
		#define STR0226 "Fundo de Reserva - Férias"
		#define STR0227 "Fundo de Reserva IESS - Férias"
		#define STR0228 "Base AFP Aporte Solidário"
		#define STR0229 "AFP Aporte Solidário"
		#define STR0230 If( cPaisLoc $ "ANG|PTG", "Base Integral Férias ", "Base Integral Ferias " )
		#define STR0231 If( cPaisLoc $ "ANG|PTG", "Base Proporcional Férias", "Base Proporcional Ferias" )
		#define STR0232 "Dev. Imposto Fér"
		#define STR0233 "Pagamento de Juros de Antiguidade"
		#define STR0234 If( cPaisLoc $ "ANG|PTG", "Base indenização término antecipado de contrato", "Base Indenização Termino Antecipado de Contrato" )
		#define STR0235 If( cPaisLoc $ "ANG|PTG", "Valor Indenização Término Antecipado de Contrato", "Valor Indenização Termino Antecipado de Contrato" )
		#define STR0236 If( cPaisLoc $ "ANG|PTG", "Dev. Medicina Pré-paga colaborador", "Dev. Medicina Pre-paga funcionario" )
		#define STR0237 If( cPaisLoc $ "ANG|PTG", "Dev. Medicina Pré-paga empresa", "Dev. Medicina Pre-paga empresa" )
		#define STR0238 "Falta de domingo"
		#define STR0239 If( cPaisLoc $ "ANG|PTG", "Liquidação Provisão Indenização ", "Baixa Provisão Indenização " )
		#define STR0240 If( cPaisLoc $ "ANG|PTG", "Prorrogação do Aux. Maternidade", "Prorrogacao do Aux. Maternidade" )
		#define STR0241 If( cPaisLoc $ "ANG|PTG", "Pgt. de Médias Prorrogação do Aux. Maternidade", "Pagto de Medias Prorrogacao do Aux. Maternidade" )
		#define STR0242 If( cPaisLoc $ "ANG|PTG", "Férias pagas", "Ferias Pagas" )
		#define STR0243 "Baixa Provisao Cesantia"
		#define STR0244 "Baixa Provisao Intereses de Cesantia"
		#define STR0245 "Baixa Provisao Primas"
		#define STR0246 If( cPaisLoc $ "ANG|PTG", "Indenização por gravidez", "Indenização por Gravidez" )
		#define STR0247 "UPC Adicional"
		#define STR0248 If( cPaisLoc $ "ANG|PTG", "Base Total Fundo Solidário", "Base Total Fundo Solidario" )
		#define STR0249 If( cPaisLoc $ "ANG|PTG", "Adicional de Obra Social - Colaborador", "Adicional de Obra Social - Funcionário" )
		#define STR0250 If( cPaisLoc $ "ANG|PTG", "Adicional ANSSAL - Colaborador", "Adicional ANSSAL - Funcionário" )
		#define STR0251 "Adicional Obra Social - Patronal"
		#define STR0252 "Adicional ANSSAL - Patronal"
		#define STR0253 "Adicional Obra Social  Vacaciones  - Funcionario"
		#define STR0254 "Adicional ANSSAL Vacaciones  - Funcionario"
		#define STR0255 "Adicional Obra Social  Vacaciones  - Patronal"
		#define STR0256 "Adicional ANSSAL  Vacaciones  - Patronal"
		#define STR0257 If( cPaisLoc $ "ANG|PTG", "Adicional Obra Social  SAC  - Colaborador", "Adicional Obra Social  SAC  - Funcionario" )
		#define STR0258 If( cPaisLoc $ "ANG|PTG", "Adicional ANSSAL SAC  - Colaborador", "Adicional ANSSAL SAC  - Funcionario" )
		#define STR0259 "Adicional Obra Social  SAC  - Patronal"
		#define STR0260 "Adicional ANSSAL SAC  - Patronal"
		#define STR0261 "Base Dif. Obra Social Vacaciones"
		#define STR0262 "Dev. Dif.  Plan de Salud"
		#define STR0263 "Base Valor Ganancia Vacaciones"
		#define STR0264 "BS Adic Obra Social Vaciones - Funcionário"
		#define STR0265 "BS Adic ANSSAL Vaciones - Funcionário"
		#define STR0266 "Devolucíon de SAC Pago Mayor al Empleado"
		#define STR0267 "Gratificação Extraordinária"
		#define STR0268 "Gratificação Extraordinária - Diferença"
		#define STR0269 "Bono Cota Cero"
		#define STR0270 "Gratificação Extraordinária na Rescisão"
		#define STR0271 "Infotep Utilidades"
		#define STR0272 "Infotep Folha de Pagamento"
		#define STR0273 If( cPaisLoc $ "ANG|PTG", "Base Salário para Licenças (Maternidade, Doença e Subsídio Seguro)", "Base Salario para Licenças (Maternidade, Enfermidade e Subsídio Seguro)" )
		#define STR0274 If( cPaisLoc $ "ANG|PTG", "Base Salário para Quinquênio", "Base Salario para Quinquenio" )
		#define STR0275 If( cPaisLoc $ "ANG|PTG", "Quinquênio por Roteiro", "Quinquenio por Roteiro" )
		#define STR0276 If( cPaisLoc $ "ANG|PTG", "Quinquênio fora do prazo", "Quinquenio fora do prazo" )
		#define STR0277 If( cPaisLoc $ "ANG|PTG", "Subsídio de fronteira", "Subsídio de Fronteira" )
		#define STR0278 "Deduccion por Dependientes"
		#define STR0279 If( cPaisLoc $ "ANG|PTG", "Base CNS Seguro a curto prazo", "Base CNS Seguro a corto prazo" )
		#define STR0280 "Distribuição de Lucro 1ª Parcela (Desconto)"
		#define STR0281 If( cPaisLoc $ "ANG|PTG", "Ded.Remun.Maternidade", "Ded.  Sal Maternidade" )
		#define STR0282 "Periculosidade sobre verbas"
		#define STR0283 "Insalubridade sobre verbas"
		#define STR0284 "Anuênio sobre verbas"
		#define STR0285 "Biênio sobre verbas"
		#define STR0286 "Triênio sobre verbas"
		#define STR0287 "Quadriênio sobre verbas"
		#define STR0288 "Quinquênio sobre verbas"
		#define STR0289 "ATS 13.Salário"
		#define STR0290 "ATS 13.Salário sobre verbas"
		#define STR0291 If( cPaisLoc $ "ANG|PTG", "Periculosidade Subs.Natal", "Periculosidade 13.Salário" )
		#define STR0292 "Periculosidade 13.Salário sobre verbas"
		#define STR0293 If( cPaisLoc $ "ANG|PTG", "Insalubridade Subs.Natal", "Insalubridade 13.Salário" )
		#define STR0294 "Insalubridade 13.Salário  sobre verbas"
		#define STR0295 If( cPaisLoc $ "ANG|PTG", "Adicional Cargo de Confiança Subs.Natal", "Adicional Cargo de Confiança 13.Salário" )
		#define STR0296 If( cPaisLoc $ "ANG|PTG", "Adicional Transferência Subs.Natal", "Adicional Transferencia 13.Salário" )
		#define STR0297 "ATS Férias Mês"
		#define STR0298 "ATS Férias Mês Seguinte"
		#define STR0299 "ATS Férias Mês s/ Verbas"
		#define STR0300 "ATS Férias Mês Seg. s/ Verbas"
		#define STR0301 "Periculosidade Férias Mês"
		#define STR0302 "Periculosidade Férias Mês Seg."
		#define STR0303 "Periculosidade Férias Mês s/ Verbas"
		#define STR0304 "Periculosidade Férias Mês Seg. s/ Verbas"
		#define STR0305 "Insalubridade Férias Mês"
		#define STR0306 "Insalubridade Férias Mês Seg."
		#define STR0307 "Insalubridade Férias Mês s/ Verbas"
		#define STR0308 "Insalubridade Férias Mês Seg. s/ Verbas"
		#define STR0309 "Adic. Cargo Confiança Férias Mês"
		#define STR0310 "Adic. Cargo Confiança Férias Mês Seg."
		#define STR0311 "Adic. Transferência Férias Mês"
		#define STR0312 "Adic. Transferência Férias Mês Seg."
		#define STR0313 "ATS Abono Mês"
		#define STR0314 "ATS Abono Mês Seg."
		#define STR0315 "ATS Abono Mês s/ Verbas"
		#define STR0316 "ATS Abono Mês Seg. s/ Verbas"
		#define STR0317 "Periculosidade Abono Mês"
		#define STR0318 "Periculosidade Abono Mês Seg."
		#define STR0319 "Periculosidade Abono Mês s/ Verbas"
		#define STR0320 "Periculosidade Abono Mês Seg. s/ Verbas"
		#define STR0321 "Insalubridade Abono Mês"
		#define STR0322 "Insalubridade Abono Mês Seg."
		#define STR0323 "Insalubridade Abono Mês s/ Verbas"
		#define STR0324 "Insalubridade Abono Mês Seg. s/ Verbas"
		#define STR0325 "Adic. Cargo Confiança Abono Mês"
		#define STR0326 "Adic. Cargo Confiança Abono Mês Seg."
		#define STR0327 "Adic. Transferencia Abono Mês"
		#define STR0328 "Adic. Transferência Abono Mês Seg."
		#define STR0329 "IR PLR Mês Anterior (Base)"
		#define STR0330 "Arredondamento do Adiantamento (Provento)"
		#define STR0331 "DSR sobre Medias Abono"
		#define STR0332 "DSR sobre Medias Abono Mes Seguinte"
		#define STR0333 "Licenca Premio - Gozo"
		#define STR0334 "Licenca Premio - Indenizacao"
		#define STR0335 "Exercicio Cumulativo"
		#define STR0336 "Ferias Compensatorias"
		#define STR0337 "Subsidio Isento de IRPF"
		#define STR0338 "Plantao Indenizado"
		#define STR0339 "ATS Maternidade"
		#define STR0340 "Insalubridade Maternidade"
		#define STR0341 "Periculosidade Maternidade"
		#define STR0342 "Adic. Cargo Confiança Maternidade"
		#define STR0343 "Adic. Transferencia Maternidade"
		#define STR0344 "Contribuição Voluntária AFC"
		#define STR0345 "Contribuição Voluntária AFP"
		#define STR0346 "Contribuição Voluntário que participa na Retenção Contingente"
		#define STR0347 "Retenção Contigente"
		#define STR0348 "Retenção na fonte Sem Contribuições Voluntárias"
		#define STR0349 "Retenção na fonte Com Contribuições Voluntárias"
		#define STR0350 "Aux. Enfermidade Profissional"
		#define STR0351 "Enfermidade profissional CNS"
		#define STR0352 "Prorrogação - ATS Maternidade"
		#define STR0353 "Prorrogação - Insalubridade Maternidade"
		#define STR0354 "Prorrogação - Periculosidade Maternidade"
		#define STR0355 "Prorrogação - Adic. Cargo Confiança Maternidade"
		#define STR0356 "Prorrogação - Adic. Transferencia Maternidade"
		#define STR0357 "Contribuição Voluntário AFP Empresa"
		#define STR0358 "Contribuição FSP Solidariedade"
		#define STR0359 "Contribuição FSP Subsistência"
		#define STR0360 "Contribuição ESAP"
		#define STR0361 "Contribuição MEN"
		#define STR0362 "Valor Não Retido Contribuição Voluntária"
		#define STR0363 "Valor UPC Adicional"
		#define STR0364 "Devolução Faltas II"
		#define STR0365 "Faltas III"
		#define STR0366 "Faltas IV"
		#define STR0367 "Devolução Faltas III"
		#define STR0368 "Devolução Faltas IV"
		#define STR0369 "Redução de Jornada"
		#define STR0370 "Abono Permanencia"
		#define STR0371 "Redutor de Teto"
		#define STR0372 "Vale Cultura (Provento)"
		#define STR0373 "Vale Cultura (Desconto)"
		#define STR0374 "Substituições"
		#define STR0375 "Prev. Propria Desconto - RPPS"
		#define STR0376 "Subsidio Proporcional CNE"
		#define STR0377 "Total Percepcion Gravada"
		#define STR0378 "Dias Horas Extras Dobles"
		#define STR0379 "Dias Horas Extras Triples"
		#define STR0380 "Ferias Indenizadas em Folha"
		#define STR0381 "Adicionais Ferias Indenizadas em Folha"
		#define STR0382 "Abono Permanencia Retroativo"
		#define STR0383 "Prev. Propria Desconto 13o. - RPPS"
		#define STR0384 "Vacaciones Progresivas"
		#define STR0385 "Base Inss Contr. Indiv. Cooperado"
		#define STR0386 "Salário Contribuição Após a Desoneração (13o.Sal.)"
		#define STR0387 "Complemento de Vale Alimentação - Provento"
		#define STR0388 "Complemento de Vale Alimentação - Desconto"
		#define STR0389 "Complemento de Vale Alimentação - Empresa"
		#define STR0390 "Complemento de Vale Refeição - Provento"
		#define STR0391 "Complemento de Vale Refeição - Desconto"
		#define STR0392 "Complemento de Vale Refeição - Empresa"
		#define STR0393 "Complemento de Vale Transporte - Provento"
		#define STR0394 "Complemento de Vale Transporte - Desconto"
		#define STR0395 "Complemento de Vale Transporte - Empresa"
		#define STR0396 "Contribuição Adicional Senai"
		#define STR0397 "Contribuição Adicional Senai Dissídio"
		#define STR0398 "Redução Salário - PPE"
		#define STR0399 "Abono FAT - PPE"
		#define STR0400 "Dominical Adicional"
		#define STR0401 "DSR Saldo Salario"
		#define STR0402 "Provisao de Recesso"
		#define STR0403 "Correcao Provisao Recesso"
		#define STR0404 "Baixa Provisao Recesso"
		#define STR0405 "Baixa Prov. Recesso Transf"
		#define STR0406 "Baixa Prov. Recesso Rescisao"
		#define STR0407 "Pagto Peric. Sobre Medias Ferias Mes Seguinte"
		#define STR0408 "Pagto Insalub. Sobre Medias Ferias Mes Seguinte"
		#define STR0409 "Pagto Peric. Sobre Medias Abono"
		#define STR0410 "Pagto Insalub. Sobre Medias Abono"
		#define STR0411 "Pagto Peric. Sobre Medias Abono Mes Seguinte"
		#define STR0412 "Pagto Insalub. Sobre Medias Abono Mes Seguinte"
		#define STR0413 "Liquido valores extras"
		#define STR0414 "Devolucao Inss (Ferias com aliquota superior)"
		#define STR0415 "Autonomo MEI sem INSS"
		#define STR0416 "Auxílio-Creche com Imposto de Renda"
		#define STR0417 "Licença Remunerada"
		#define STR0418 "1 Parc. 13 Antecipado mesmo mes rescisão"
		#define STR0419 "Dif Media Horas sobre Abono"
		#define STR0420 "Dif Media Valor sobre Abono"
		#define STR0421 "Dif Media Horas sobre Abono Mes seg."
		#define STR0422 "Dif Media valor sobre Abono Mes seg."
		#define STR0423 "Reservado"
		#define STR0424 "Valor de afastamento por doença pago pela Previdência"
		#define STR0425 "Adicional de Confiança do Mês"
		#define STR0426 "Adicional de Transferência do Mês"
		#define STR0427 "Insalubridade Gestante"
		#define STR0428 "Recesso Indenizado"
		#define STR0429 "Recesso Proporcional"
		#define STR0430 "Base parte Empresa Diferença Assist.Medica"
		#define STR0431 "Base parte Empresa Diferença Assist.Medica Dep/Agreg."
		#define STR0432 "Base parte Empresa Diferença Assist.Odontologica"
		#define STR0433 "Base parte Empresa Diferença Assist.Odontologica Dep/Agreg."
		#define STR0434 "Pro-Labore - Diretores não empregados"
		#define STR0435 "Pro-Labore - Proprietários ou sócios"
		#define STR0436 "Valor de afastamento por acidente pago pela Previdência"
		#define STR0437 "Valor de remuneração a que teria direito (Serviço Militar)"
		#define STR0438 "1ª Parc. 13º Sal. Maternidade"
		#define STR0439 "Parcela Final 13º Sal Maternidade"
		#define STR0440 "Total de Medias em Valor Maternidade"
		#define STR0441 "Total de Medias em Horas Maternidade"
		#define STR0442 "ATS 13. Salário Maternidade"
		#define STR0443 "ATS 13. Salário sobre verbas Maternidade"
		#define STR0444 "Periculosidade 13. Salario Maternidade"
		#define STR0445 "Periculosidade 13. Salario sobre verbas Maternidade"
		#define STR0446 "Insalubridade 13. Salario Maternidade"
		#define STR0447 "Insalubridade 13. Salario sobre verbas Maternidade"
		#define STR0448 "Adicional Cargo de Confiança 13.Salário Maternidade"
		#define STR0449 "Adicional Transferencia 13.Salário Maternidade"
		#define STR0450 "13º na Indenizacao Rescisao Maternidade"
		#define STR0451 "Media 13º Salario Rescisao Maternidade"
		#define STR0452 "Autonomo cooperado"
		#define STR0453 "Abonos Pagos Mes Anterior"
	#endif
#endif
